In [1]:
import pandas as pd
import numpy as np
import matplotlib.pyplot as plt
from sklearn import linear_model

In [2]:
df= pd.read_csv("D:\GIT1\Machine-Learning\Regression\housing.csv")
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

The regression is going to cover the Numerical(area,bedrooms,bathrooms,stories,parking) and Non-numerical features(mainroad,guestroom,basement,hotwaterheating,airconditioning,prefarea,furnishingstatus)  

In [4]:
#Numerical Features and inputs
df_num = df[['price','area','bedrooms','bathrooms','stories','parking']]
df_num

price  area  bedrooms  bathrooms  stories  parking
0    13300000  7420         4          2        3        2
1    12250000  8960         4          4        4        3
2    12250000  9960         3          2        2        2
3    12215000  7500         4          2        2        3
4    11410000  7420         4          1        2        2
..        ...   ...       ...        ...      ...      ...
540   1820000  3000         2          1        1        2
541   1767150  2400         3          1        1        0
542   1750000  3620         2          1        1        0
543   1750000  2910         3          1        1        0
544   1750000  3850         3          1        2        0

[545 rows x 6 columns]

In [5]:
#fit regression
reg = linear_model.LinearRegression()
reg.fit(df_num[['area','bedrooms','bathrooms','stories','parking']],df_num.price)

LinearRegression()

In [6]:
#getting coefficients and intercepts ---- y = m1*3.31115495e+02 + m2*1.67809788e+05 + m3*1.13374016e+06 + m4*5.47939810e+05 + m5*3.77596289e+05 - 145734.4894558806
reg.coef_ , reg.intercept_

(array([3.31115495e+02, 1.67809788e+05, 1.13374016e+06, 5.47939810e+05,
        3.77596289e+05]),
 -145734.4894558806)

In [11]:
#predicting using method 1
reg.predict([[9960,3,2,2,2]])

c:\Users\MARTIN KILOMBE\anaconda3\envs\machinelearning\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([7774157.72976678])

In [10]:
#predicting using method 2
# Predicting using named features
prediction_input = pd.DataFrame({
    'area': [9960],
    'bedrooms': [3],
    'bathrooms': [2],
    'stories': [2],
    'parking': [2]
})
prediction = reg.predict(prediction_input)
print(prediction)


[7774157.72976678]


Using linear Regression to perform predictions using the categorical and numerical features

1. Import relevant libraries
2. Data pre-processing -- oneHotecoding categorical data
3. Split data to Features(independent(X)) and Targets(dependent(y))
4. Split data into traing and test sets
5. Train model
6. Make predictions

In [3]:
import pandas as pd
from sklearn.model_selection import train_test_split
from sklearn.linear_model import LinearRegression
from sklearn.metrics import mean_squared_error

In [4]:
#Load data from csv file
df = pd.read_csv("D:\GIT1\Machine-Learning\Regression\housing.csv")
df

price  area  bedrooms  bathrooms  stories mainroad guestroom basement  \
0    13300000  7420         4          2        3      yes        no       no   
1    12250000  8960         4          4        4      yes        no       no   
2    12250000  9960         3          2        2      yes        no      yes   
3    12215000  7500         4          2        2      yes        no      yes   
4    11410000  7420         4          1        2      yes       yes      yes   
..        ...   ...       ...        ...      ...      ...       ...      ...   
540   1820000  3000         2          1        1      yes        no      yes   
541   1767150  2400         3          1        1       no        no       no   
542   1750000  3620         2          1        1      yes        no       no   
543   1750000  2910         3          1        1       no        no       no   
544   1750000  3850         3          1        2      yes        no       no   

    hotwaterheating airconditioning  parking prefarea furnishingstatus  
0                no             yes        2      yes        furnished  
1                no             yes        3       no        furnished  
2                no              no        2      yes   semi-furnished  
3                no             yes        3      yes        furnished  
4                no             yes        2       no        furnished  
..              ...             ...      ...      ...              ...  
540              no              no        2       no      unfurnished  
541              no              no        0       no   semi-furnished  
542              no              no        0       no      unfurnished  
543              no              no        0       no        furnished  
544              no              no        0       no      unfurnished  

[545 rows x 13 columns]

In [5]:
#preprocessing data -- categorical features using one-hotEncoding
df =pd.get_dummies(df,columns=['mainroad', 'guestroom', 'basement', 'hotwaterheating', 'airconditioning', 'prefarea', 'furnishingstatus'],drop_first=True)
df

price  area  bedrooms  bathrooms  stories  parking  mainroad_yes  \
0    13300000  7420         4          2        3        2             1   
1    12250000  8960         4          4        4        3             1   
2    12250000  9960         3          2        2        2             1   
3    12215000  7500         4          2        2        3             1   
4    11410000  7420         4          1        2        2             1   
..        ...   ...       ...        ...      ...      ...           ...   
540   1820000  3000         2          1        1        2             1   
541   1767150  2400         3          1        1        0             0   
542   1750000  3620         2          1        1        0             1   
543   1750000  2910         3          1        1        0             0   
544   1750000  3850         3          1        2        0             1   

     guestroom_yes  basement_yes  hotwaterheating_yes  airconditioning_yes  \
0                0             0                    0                    1   
1                0             0                    0                    1   
2                0             1                    0                    0   
3                0             1                    0                    1   
4                1             1                    0                    1   
..             ...           ...                  ...                  ...   
540              0             1                    0                    0   
541              0             0                    0                    0   
542              0             0                    0                    0   
543              0             0                    0                    0   
544              0             0                    0                    0   

     prefarea_yes  furnishingstatus_semi-furnished  \
0               1                                0   
1               0                                0   
2               1                                1   
3               1                                0   
4               0                                0   
..            ...                              ...   
540             0                                0   
541             0                                1   
542             0                                0   
543             0                                0   
544             0                                0   

     furnishingstatus_unfurnished  
0                               0  
1                               0  
2                               0  
3                               0  
4                               0  
..                            ...  
540                             1  
541                             0  
542                             1  
543                             0  
544                             1  

[545 rows x 14 columns]

In [6]:
#Split the data into features(indpendent variables) and Targets(Dependent variable)
X = df.drop('price', axis =1)
y = df['price']

In [7]:
#Split data into training and Test sets
X_train,X_test,y_train,y_test = train_test_split(X,y,test_size =0.2,random_state=42)

In [8]:
print(X_train.columns)


Index(['area', 'bedrooms', 'bathrooms', 'stories', 'parking', 'mainroad_yes',
       'guestroom_yes', 'basement_yes', 'hotwaterheating_yes',
       'airconditioning_yes', 'prefarea_yes',
       'furnishingstatus_semi-furnished', 'furnishingstatus_unfurnished'],
      dtype='object')


In [9]:
#Training the linear regression model
regressor =LinearRegression()
regressor.fit(X_train,y_train)

LinearRegression()

In [10]:
#Make predictions and model evaluation
y_pred = regressor.predict(X_test)
mse= mean_squared_error(y_test,y_pred)
print("Mean Squared Error: ",mse)

Mean Squared Error:  1754318687330.6643


In [11]:
# Prediction input with correct feature names and order
new_input = {
    'area': [9960],
    'bedrooms': [3],
    'bathrooms': [2],
    'stories': [2],
    'parking': [2],  # Make sure 'parking' is included in the correct order
    'mainroad_yes': [1],
    'guestroom_yes': [0],
    'basement_yes': [1],
    'hotwaterheating_yes': [0],
    'airconditioning_yes': [0],
    'prefarea_yes': [1],
    'furnishingstatus_semi-furnished': [1],
    'furnishingstatus_unfurnished': [0]
}

# Create a DataFrame with the same order of columns as in training data
new_input_df = pd.DataFrame(new_input, columns=X_train.columns)

# Make prediction
new_prediction = regressor.predict(new_input_df)
print("Predicted Price:", new_prediction[0])


Predicted Price: 7555324.216056033


Saving the model -- using the joblib

In [1]:
import joblib

In [12]:
#saving the model using joblib
joblib.dump(regressor,'house_prediction_model.joblib')

['house_prediction_model.joblib']

In [13]:
#Loading the model using joblib
house_prediction = joblib.load('house_prediction_model.joblib')

In [14]:
house_prediction.predict([[7500,4,2,2,3,1,0,1,0,1,1,0,0]])

c:\Users\MARTIN KILOMBE\anaconda3\envs\machinelearning\lib\site-packages\sklearn\base.py:439: UserWarning: X does not have valid feature names, but LinearRegression was fitted with feature names
  warnings.warn(


array([8194770.1252235])